import datetime
import logging
import random
import string
import uuid

from sqlalchemy.orm import Session  # Import Session type hint

from app.config import Config
from app.models.otp import OTP  # Import OTP Model
from app.utils.security_utils import hash_password

logger = logging.getLogger(__name__)
config = Config()


def generate_otp(length=config.OTP_LENGTH):
    return "".join(random.choices(string.digits, k=length))


def store_otp_in_db(otp_request_data: dict, db: Session, request_id: str):
    user_id = otp_request_data.get("user_id")
    request_id = otp_request_data.get("request_id")
    email = otp_request_data.get("email")
    country_code = otp_request_data.get("country_code")
    phone_number = otp_request_data.get("phone_number")
    otp_val = otp_request_data.get("otp")
    otp_expiry = otp_request_data.get("otp_expiry")
    request_type = otp_request_data.get("request_type")

    if not otp_val or not otp_expiry or not user_id:  # user_id is now required
        logger.error(
            f"Request ID: {request_id} - Incomplete data for storing OTP in DB. Missing OTP value, expiry, or user_id.")
        return  # Or raise an exception if you want to enforce this strictly

    otp_hash = hash_password(otp_val)  # Hash OTP with generated salt

    otp_entry = OTP(  # Use OTP Model
        id=otp_request_data.get("otp_id"),  # Allow passing existing ID, or UUID will be generated by default
        user_id=user_id,  # Associate with User ID
        country_code=country_code,
        phone_number=phone_number,
        email=email,
        otp_hash=otp_hash,  # Store the hashed OTP
        otp_expiry=otp_expiry,
        request_type=request_type,
    )
    db.add(otp_entry)  # Add the OTP entry to the session
    db.commit()  # Commit changes to DB, using injected session
    logger.debug(
        f"Request ID: {request_id} - OTP stored in DB for user_id: {user_id}, email: {email}, expiry: {otp_expiry}"
    )


def get_otp_by_user(user_id: uuid.UUID, db: Session, request_id: str):
    logger.debug(f"Request ID: {request_id} - Retrieving OTP from DB for user_id: {user_id}")
    return db.query(OTP).filter(OTP.user_id == user_id).order_by(
        OTP.otp_expiry.desc()).first()  # Get latest, order by expiry


def get_otp_by_email(db: Session, request_id: str, email: str):
    logger.debug(f"Request ID: {request_id} - Retrieving OTP from DB for email: {email}")
    return db.query(OTP).filter(OTP.email == email, OTP.status == 'pending').order_by(OTP.otp_expiry.desc()).first()


def get_otp_by_phone(db: Session, request_id: str, country_code: str, phone_number: str):
    logger.debug(
        f"Request ID: {request_id} - Retrieving OTP from DB for phone number: {phone_number}, country code: {country_code}")
    return db.query(OTP).filter(OTP.country_code == country_code, OTP.phone_number == phone_number,
                                OTP.status == 'pending').order_by(OTP.otp_expiry.desc()).first()  # Get latest


def invalidate_otp(db: Session, request_id: str, otp_entry: OTP, status: str):
    if otp_entry:
        otp_entry.status = status
        db.add(otp_entry)
        db.commit()
        logger.info(f"Request ID: {request_id} - OTP invalidated. OTP ID: {otp_entry.id}, Status set to: {status}")
    else:
        logger.warning(f"Request ID: {request_id} - invalidate_otp called with None otp_entry.")


def increment_verification_attempts(db: Session, request_id: str, otp_entry: OTP):
    if otp_entry:
        otp_entry.verification_attempts += 1
        otp_entry.last_attempt_at = datetime.datetime.now()  # Use db.func for server-side timestamp
        db.add(otp_entry)
        db.commit()
        logger.debug(
            f"Request ID: {request_id} - Verification attempt incremented for OTP ID: {otp_entry.id}. Attempts: {otp_entry.verification_attempts}")
    else:
        logger.warning(f"Request ID: {request_id} - increment_verification_attempts called with None otp_entry.")


def send_otp(request_id: str, otp: str, delivery_method: str = "log", email: str = None, country_code: str = None,
             phone_number: str = None):
    if delivery_method == "phone":
        if not (country_code and phone_number):
            logger.error(f"Request ID: {request_id} - Missing country_code or phone_number for SMS delivery.")
            return
        full_phone_number = f"{country_code}{phone_number}"
        # TODO: Implement SMS sending logic using an SMSService
        logger.warning(f"Request ID: {request_id} - SMS sending not yet implemented. Cannot send OTP - {otp} to phone:"
                       f" {full_phone_number}")
        # Placeholder for SMS sending: sms_service.send_otp_sms(phone_number, country_code, otp)
    elif delivery_method == "email":
        if not email:
            logger.error(f"Request ID: {request_id} - Missing email for OTP delivery via email.")
            return
        try:
            # email_service.send_otp_email(otp=otp, email=email, request_id=request_id)
            logger.info(f"Request ID: {request_id} - OTP: {otp} sending initiated via email for: {email}")
        except Exception as e:
            logger.error(f"Request ID: {request_id} - Error sending OTP via email: {str(e)}")
    elif delivery_method == "log":
        logger.critical(f"Request ID: {request_id} - OTP: {otp} for: {country_code}{phone_number}/{email}")
    else:
        logger.error(f"Request ID: {request_id} - Invalid delivery method: {delivery_method}")
